Switch to cgroupv1 (#201)
* Switch to cgroupv1

* change wording

* warn user

* fix if statement

diff --git a/homeassistant-supervised/DEBIAN/postinst b/homeassistant-supervised/DEBIAN/postinst
--- a/homeassistant-supervised/DEBIAN/postinst
+++ b/homeassistant-supervised/DEBIAN/postinst
@@ -131,7 +131,19 @@ systemctl start hassio-supervisor.service
 info "Installing the 'ha' cli"
 chmod a+x "${PREFIX}/bin/ha"
 
+# Switch to cgroup v1
+if ! grep -q "systemd.unified_cgroup_hierarchy=false" /etc/default/grub; then
+    info "Switching to cgroup v1"
+    cp /etc/default/grub /etc/default/grub.bak
+    sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&systemd.unified_cgroup_hierarchy=false /' /etc/default/grub
+    update-grub
+    touch /var/run/reboot-required
+fi
 
 info "Within a few minutes you will be able to reach Home Assistant at:"
 info "http://homeassistant.local:8123 or using the IP address of your"
 info "machine: http://${IP_ADDRESS}:8123"
+if [ -f /var/run/reboot-required ]
+then
+    warn "A reboot is required to apply changes to grub."
+fi
